# Importing the libraries

In [31]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import pandas as pd
import plotly.express as px
from datetime import datetime
from datetime import timedelta
from matplotlib.backends.backend_pdf import PdfPages
from tqdm import tqdm
import logging
import plotly.figure_factory as ff
import os

import seaborn as sns
%matplotlib inline

import plotly.express as px
import plotly.graph_objs as go
import plotly
import plotly.offline as pyo
import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

import plotly.offline as pyo
import plotly.graph_objs as go
from bokeh.plotting import *
from bokeh.models import *
from bokeh.plotting import figure, show
from bokeh.models import LinearAxis, Range1d, Legend
import bokeh.io
bokeh.io.reset_output()
# bokeh.io.output_notebook()

pd.set_option('display.float_format', lambda x: f'{x:.3f}')

# Importing the dataset

In [32]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [33]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.000              1          1               1   
1       1  83807.860              1          0               1   
2       8 159660.800              3          1               0   
3       1      0.000              2          0               0   
4       2 125510.820              1          1               1   

   EstimatedSalary  Exited  
0       101348.880       1  
1       112542.580       0  
2       113931.570       1  
3        93826.630       0  
4        79084.100       0

In [34]:
import tensorflow as tf

In [35]:
tf.__version__

'2.10.0'

# Encoding categorical data

In [36]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [37]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [38]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])]
                       ,remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [39]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into the Training set and Test set

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2, random_state = 0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

In [42]:
ann = tf.keras.models.Sequential()

In [43]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN

In [44]:
ann.compile(optimizer='adam' ,loss='binary_crossentropy',
            metrics=['accuracy'])

In [45]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 544us/step - loss: 0.5078 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 536us/step - loss: 0.4574 - accuracy: 0.7971
Epoch 3/100
250/250 [==============================] - 0s 519us/step - loss: 0.4433 - accuracy: 0.7980
Epoch 4/100
250/250 [==============================] - 0s 510us/step - loss: 0.4354 - accuracy: 0.8011
Epoch 5/100
250/250 [==============================] - 0s 511us/step - loss: 0.4282 - accuracy: 0.8058
Epoch 6/100
250/250 [==============================] - 0s 536us/step - loss: 0.4189 - accuracy: 0.8156
Epoch 7/100
250/250 [==============================] - 0s 537us/step - loss: 0.4076 - accuracy: 0.8200
Epoch 8/100
250/250 [==============================] - 0s 561us/step - loss: 0.3979 - accuracy: 0.8236
Epoch 9/100
250/250 [==============================] - 0s 535us/step - loss: 0.3896 - accuracy: 0.8282
Epoch 10/100
250/250 [==============================] - 0s 535us/step - l

250/250 [==============================] - 0s 519us/step - loss: 0.3384 - accuracy: 0.8615
Epoch 80/100
250/250 [==============================] - 0s 498us/step - loss: 0.3381 - accuracy: 0.8619
Epoch 81/100
250/250 [==============================] - 0s 515us/step - loss: 0.3383 - accuracy: 0.8600
Epoch 82/100
250/250 [==============================] - 0s 505us/step - loss: 0.3385 - accuracy: 0.8612
Epoch 83/100
250/250 [==============================] - 0s 503us/step - loss: 0.3383 - accuracy: 0.8622
Epoch 84/100
250/250 [==============================] - 0s 510us/step - loss: 0.3375 - accuracy: 0.8629
Epoch 85/100
250/250 [==============================] - 0s 544us/step - loss: 0.3378 - accuracy: 0.8624
Epoch 86/100
250/250 [==============================] - 0s 528us/step - loss: 0.3382 - accuracy: 0.8631
Epoch 87/100
250/250 [==============================] - 0s 511us/step - loss: 0.3381 - accuracy: 0.8618
Epoch 88/100
250/250 [==============================] - 0s 505us/step - loss:

# Making the predictions and evaluating the model

In [46]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 43ms/step
[[False]]


# Predicting the Test set results

In [47]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 485us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1502   93]
 [ 191  214]]


0.858